### PR TITLE
1674 add search title in json data

### LINKED ISSUE #1674: Add search title in JSON data
### Description

Add search title of life event in JSON data.

Image

### User Story

_No response_

### Acceptance Criteria

Search title added into JSON data

### PR DESCRIPTION
**Pull request by gchi25**
## PR Summary

This work add search title in json data.

## Related Github Issue

- Fixes #1674

## Detailed Testing steps

To test in local development site or in dev site.

- [ ] In local, pull changes locally
- [ ] In local, make local development site up at http://localhost
- [ ] Navigate to `admin/content?combine=&type=bears_life_event&status=All&langcode=All`
- [ ] Go to life event "Benefit finder: retirement" edit page
- [ ] Add "Approaching retirement" in search title field
- [ ] Save as published
- [ ] Go to life event "Benefit finder: disability" edit page
- [ ] Add "Living with a disability or illness" in search title field
- [ ] Save as published
- [ ] Navigate to `benefit-finder/api/life-event/death`
- [ ] Verify searchTitle in json data

image

after generating json
- [ ] navigate to "/benefit-finder/death`
- [ ] complete required fields to get to Results view
- [ ] ensure updated searchTitles are rendering in Relevant Benefits Cards

Screenshot 2024-08-20 at 10 44 51 AM

### CODE REVIEW

**Comment by scottqueen-bixal** [comment]
Requirement is for the new key pair to be in the `relevantBenefits` Array Objects

Screenshot 2024-08-15 at 9 40 04 AM

**Review by scottqueen-bixal — COMMENTED** [review]
Check location of key

**Review by scottqueen-bixal — CHANGES_REQUESTED** [review]
Check location of key

**Comment by gchi25** [comment]
> Requirement is for the new key pair to be in the `relevantBenefits` Array Objects
> 
> Screenshot 2024-08-15 at 9 40 04 AM

Implemented.

**Comment by scottqueen-bixal** [comment]
I've included the update for consuming the new `searchTitle` with the `title` fall back in the application.

**Review by scottqueen-bixal — APPROVED** [review]

**Comment by gchi25** [comment]
Tested. Worked as expected.

http://localhost/benefit-finder/death?applicant_date_of_birth=%7B%22month%22%3A%220%22%2C%22day%22%3A%221%22%2C%22year%22%3A%221960%22%7D&applicant_relationship_to_the_deceased=Spouse&applicant_marital_status=Married&deceased_date_of_death=%7B%22month%22%3A%224%22%2C%22day%22%3A%2230%22%2C%22year%22%3A%222020%22%7D&shared=true

image

**Pull request merged**
